### ISSUE TITLE
_passWordField.secureTextEntry = NO; 的问题。

### ISSUE THREAD

**Issue by fei1234** [indulgeIn/YBInputControl#1]
由_passWordField.secureTextEntry = NO;
切换到 _passWordField.secureTextEntry =YES;
就有问题了，就可以输入中文了。（我设置的是YBTextControlType_number类型）。

**Comment by indulgeIn** [comment]
应该是其他错误导致的问题而不是框架的，比如两次_passWordField是不同内存.
