### ISSUE TITLE
高亮状态的内容也会被截取

### ISSUE THREAD

**Issue by zxFlyer** [indulgeIn/YBInputControl#2]
输入的时候如果最后剩余的字数，小于正在输入的拼音的高亮数，拼音无法输入，没办法打字了。
如果最后只剩下一个字的位置，这个时候打了两个字，则不可输入。
可以针对高亮的不进行截取，输入完成后再截取吗？

**Comment by indulgeIn** [comment]
YBInputControlProfile 类有个 cancelTextLengthControlBefore 属性设置为true可以解决你的问题

**Comment by zxFlyer** [comment]
```
    //长度判断
    if (profile.maxLength != NSUIntegerMax) {
        if (!profile.cancelTextLengthControlBefore && resultStr.length > profile.maxLength) {
            return NO;
        }
    }
```
你好，你这里写的cancelTextLengthControlBefore设置为YES就不判断最大长度了，设置的最大长度就无效了
